### ISSUE TITLE
Support Servers and DiscoveredServers APIs

### ISSUE THREAD

**Issue by mcqueary** [nats-io/node-nats#103]
See https://github.com/nats-io/go-nats/issues/214

**Comment by StarpTech** [comment]
Would this feature allow to enable additional server in the cluster without restarting the clients?

**Comment by aricart** [comment]
Yes!!

**Comment by StarpTech** [comment]
@aricart does exist a roadmap when can we expect this feature? Thanks.

**Comment by aricart** [comment]
It is the highest priority for node-nats.
