### ISSUE TITLE
Is it possible to detect if any subscriber received my message?

### ISSUE THREAD

**Issue by ericholiveira** [nats-io/node-nats#107]
After publishing a message i wanted to know if any subscriber received it, is it possible?

**Comment by aricart** [comment]
@ericholiveira the only way for you to know if someone got it would be to send the message as a request/reply.
If you needed to know that at least one client got the message, you would:

```
// Request with Auto-Unsubscribe. Will unsubscribe after the first response is received via {'max':1} 
nats.request('help', null, {'max':1}, function(response) {
  console.log('Got a response for help: ' + response);
});
```

The clients for the request are normal subscribers. They simply use the replyTo inbox subject to send the response:
```
// Replies
nats.subscribe('help', function(request, replyTo) {
  nats.publish(replyTo, 'I can help!');
});
```

Hope it helps.
