### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#112]
Hi,

in file `pub_perf.js` replace this line

```js
nats.publish('test', invalid2octet, () => {   });
```

after this my node processes will rise to ~1,028.8MB and freezes.

Node: v6.9.2
Windows

**Comment by StarpTech** [comment]
Anyone? :)

**Comment by kozlovic** [comment]
@StarpTech Alberto is on vacation so I will probably make a fool of myself since I don't know much about node.js, but it looks like you provide a callback function to the publish call, which means that the library will send a PING and when getting a PONG from the server, invokes this callback.
My understanding of node.js is that it is single threaded, and I am just wondering if you are not causing the library to accumulate those callbacks for the entire number of messages you are trying to send since the test program does not give back control to the event loop that would process the incoming PONs and invoke those callbacks. 
Again, I probably talk nonsense and you may have to wait for Alberto to come back next week unless @derekcollison can have a look?

**Comment by derekcollison** [comment]
I will try to take a look.

**Comment by derekcollison** [comment]
What is the code trying to accomplish? And can you send me the complete file as an attachment?

**Comment by StarpTech** [comment]
@derekcollison this happens during a simple benchmark I wanted to bench publishing with a callback.

https://gist.github.com/StarpTech/cd649380f5aebc4f9410b41fb04b2de8

While doing this observe the process manager.

**Comment by StarpTech** [comment]
I found the memory leak its in the `flush` method. `this.pongs` is the villain.

After `loop=10`
```
E:\Repositorys\node-nats>node benchmark\pub_perf.js
Publish Performance Test
[]
+[ [Function] ]
[ [Function], [Function] ]
[ [Function], [Function], [Function] ]
[ [Function], [Function], [Function], [Function] ]
[ [Function], [Function], [Function], [Function], [Function] ]
  [Function],
  [Function],
  [Function],
  [Function] ]
[ [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function] ]
[ [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function] ]
[ [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function] ]
[ [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function],
  [Function] ]
```

**Comment by kozlovic** [comment]
@StarpTech Sorry, but if you look at my previous comment, I think you are proving my point. You are setting a callback to be invoked after the message and a PING is sent to server, which server sends a PONG back. But the test program is such that the processing of inbound can never happen, so all the PONGs and therefore callbacks accumulate.
The Node event loop has no chance to process inbound data in this case.

**Comment by StarpTech** [comment]
@kozlovic thanks make sense but it still an issue and how we can solve it?

**Comment by kozlovic** [comment]
It is not an issue of nats-node, it is the way Node.js works.

There is a single event loop to which you provide data to be written and callbacks to be invoked when read events occur.

If you try to send as much data as possible without letting the event loop call you back with read events, all reads will be delayed.

As an application writer, you would need to pace your sends to give a chance to the event loop to do its work.

**Comment by kozlovic** [comment]
And pacing does not make sense in a pub benchmark test ;-) so providing a callback which by the way results in a round-trip message with the server, is not a good idea in this context.

**Comment by derekcollison** [comment]
I commented on the code snippet you sent. Depending on what you are trying to do..

1. Just use 1 flush at the end, that guarantees all messages have been received and processed.
2. Have the for loop bound to a maximum number it can send, and flush after that and use a timer to kick off the next batch.

What are you trying to optimize for?

**Comment by StarpTech** [comment]
At first I just use the Api. You can provide a callback with the `publish` method.
I understand why it fails but this looks like a bad implementation and this can't be a restriction in NodeJs.
NodeJs is single thread but it's an event loop.

Even this code fails:

```js
nats.on('connect', function() {

  for (var i=0; i<loop; i++) {
    
    nats.publish('test', 'fooBar', function () {
      nats.flush()
    });
    
  }

});
```

**Comment by StarpTech** [comment]
NodeJs ist faster in increasing the heap as nats can flushing.

**Comment by derekcollison** [comment]
Again you are starving the event loop here, and you are essentially doing two flushes. One is via the attached closure function, the other the direct call.

**Comment by StarpTech** [comment]
Can you give me an example which works?

**Comment by derekcollison** [comment]
What are you trying to optimize for? What is it that you are trying to achieve?

**Comment by StarpTech** [comment]
I have no use case I just faced with this issue by passing a callback. After I understand the limitation its fine but I think this can be avoided when the driver will be implemented async by design like https://github.com/postwait/node-amqp

It is uncommon to use the callback to check if my message was successfully proceed by NATS? When no you can imagine a IOT device which send lot of messages how can I avoid this issue when I would do it?

**Comment by StarpTech** [comment]
Just as an example this driver has a really nice implementation it has a socket oriented api.
https://github.com/squaremo/rabbit.js

Very worth to read
https://github.com/substack/stream-handbook

**Comment by StarpTech** [comment]
@derekcollison @aricart  interesting in rewrite the driver as a socket oriented api like this [article](https://nodesource.com/blog/understanding-object-streams#whereareobjectstreamsuseful) described ?

**Comment by derekcollison** [comment]
Probably not at this time. The node client is one of the most popular and works on many different versions of Node.js.

**Comment by StarpTech** [comment]
@derekcollison could you answer my question?

**Comment by derekcollison** [comment]
This is not a Node.js issue or a NATS issue per se, its a generalized messaging pattern. You should understand if the publisher cares about whether the message was processed or not. I have been doing messaging systems now for almost 25yrs, so I may have a different opinion than most. If you care, do a request/response pattern with a timeout, if you don't care, then really don't care.

**Comment by StarpTech** [comment]
I trust in your experience and expertise this is no topic to discuss I don't understand the current behaviour.  Exposing an interface which can easily run in a memory leak should be maintained by the driver. This would also implicit that all other NATS driver behave exactly the same and will run into the same issue?  Could you explain me the pattern?  Thanks.

**Comment by derekcollison** [comment]
The pattern is normal, but if you want a response you need to have platforms like Node.js that are (essentially) single threaded, return to the event loop. That is not specific to NATS.

**Comment by StarpTech** [comment]
Hi @derekcollison @kozlovic @aricart  I investigate some time to analyze how the driver is implemented. If you publish something the whole event loop is blocked https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L766 no matters whether you passed a callback or not. IO must be implemented async. You can check it easily if you log something after the for loop in a benchmark test file or if you can also check https://github.com/tj/node-blocked.
Every use of this implementation in an environment will block the whole application and can lead to fatal issues.

**Comment by StarpTech** [comment]
Hi @derekcollison I got the point now. Thank you for your patience.

**Comment by derekcollison** [comment]
No problem..
