### ISSUE TITLE
Feature: Add data compression

### ISSUE THREAD

**Issue by xsellier** [nats-io/node-nats#116]
Since we send everything in clear text we use a large network bandwidth on AWS.

By using zlib and base64 encoding, we should be able to compress/decompress easily (http://devdocs.io/node~6_lts/zlib).

A better alternative would be [msgpack5](https://www.npmjs.com/package/msgpack5)

**Comment by aricart** [comment]
This also means that all NATS client implementations must support compression. Given that NATS messages can simply be considered as a bag of bytes, it is easy for your applications to compress/decompress as necessary (simply compress before publishing/decompress on receiving a message).

**Comment by xsellier** [comment]
I get your point. I have not thought of other clients.

We will implement it on our application side.

**Comment by xsellier** [comment]
List of available implementation of [msgpack5 for different languages](http://msgpack.org/index.html)
