### ISSUE TITLE
Add Timeout and default max=1 to requests

### ISSUE THREAD

**Issue by MichaelErmer** [nats-io/node-nats#121]
The GO implementation has a timeout option and sets max to 1 by default: https://github.com/nats-io/go-nats/blob/master/nats.go#L1848

We are using nats very heavily lately and had to find out about max:1 the hard way, after multiple server crashes at about ~3M subscriptions.

I think its unintuitive that there is no default max value, it would also be good to have a timeout option like GO to get rid of stale requests, ie when the processing server is crashing during the request.

**Comment by aricart** [comment]
In node the current pattern is this:

```var nats = require('nats').connect();

ssid = nats.request('foo', '', {max:1}, function(msg) {
  console.log('response: ' + msg);
});
nats.timeout(ssid, 1000, 1, function(ssid) {
  console.log('ssid ' + ssid + ' timed out');
});```

The issue here is that while in your use case you want to unsubscribe as soon as you get one response, the code in the wild may be expecting N number of responses. So the change will break existing clients that upgrade.
