### ISSUE TITLE
Implement Streams2 Interface

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#129]
Hi,
the driver is good and it works but in the point of view of the implementation there are many things which can be refactored. We should start to develop a much more efficient and modern driver. The reference system is https://github.com/mqttjs/MQTT.js they have to meet the same requirements. They implement his driver in a more nodejs way. The fact that node-nats is the base of stan it is much more important.

Goals:
- [ ] Stream2 interface- use Pull Streams instead Push-Streams (Non-flowing)
- [ ] Create protocol parser

New approaches 
https://gist.github.com/caike/ebccc95bd46f5fa1404d
https://strongloop.com/strongblog/whats-new-io-js-beta-streams3/
http://ey3ball.github.io/posts/2014/07/17/node-streams-back-pressure/
https://howtonode.org/streams-explained

WDYT?

**Comment by derekcollison** [comment]
We try to optimize for performance, do you have a sense on whether or not there would be a performance gain with the new approach? What is the minimum Node.js version that would be supported with this new approach?

**Comment by aricart** [comment]
I am interested in understanding what you mean by 'Create message parser'. Can you please elaborate a bit more?

**Comment by StarpTech** [comment]
Hi @derekcollison I don't just talk about performance. I do not any tests but I'm optimistic that implementing a driver with the stream2 interface would lead to a much better abstaction. One big advantage is that stream2 handle buffering and backpressure automatically.

Hi @aricart Im talking about a protocol parser instead to use regex so we can outsource the relevant parts and optimize it in lots of facts not just performance. I think it would clean it up if we implement it in the node way. 
Example https://github.com/mqttjs/mqtt-packet

**Comment by aricart** [comment]
So basically you want to externalize the parser so that you can inject your own. Is that right? [I wonder what it means for the message ordering to externalize it and make it an event emitter.]

I am also wondering what the optimizations would do? One thing that I am missing is the trigger for this request. While I am hearing that it could be faster, I am yet to see the metrics showing that this is where we can make it faster - or for that matter that it is slow. Note that I am all for making it as fast as possible. But it would be good to have some additional discussion as to why we want to change the internal of how node-nats works without additional supporting information to motivate a change.

**Comment by StarpTech** [comment]
I dont want to inject my own. I talk about to clean up the code.
Thats the reason why I open this issue so we can discuss about it.

**Comment by StarpTech** [comment]
The benefits of the stream2 interface compared to the old interface you can find in the links.

**Comment by aricart** [comment]
Can you motivate me in terms of actual throughput with the given implementation? While the new interfaces may in theory be faster, realize that the gains should be significant and somehow measurable.

**Comment by StarpTech** [comment]
If you have 5min see the presenation of Isaac Z. https://dl.dropboxusercontent.com/u/3685/presentations/streams2/streams2-ko.pdf really worth reading. After that you can compare our current implementation better.

**Comment by StarpTech** [comment]
@aricart Do you know understand the benefits of stream2 interface?

**Comment by aricart** [comment]
Yes I do. Could you contribute a patch that changes the API to use stream2 so that we can measure the difference in performance?

**Comment by StarpTech** [comment]
At the moment my time is very limited but I will try to prepare something.

**Comment by aricart** [comment]
The transport is externalized in ts-nats, and likely it is possible to create an implementation there that will do the needed.
