### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by imatefx** [nats-io/node-nats#132]
Can you release a new version?, the issue is already fixed, but i am forced to use the package from latest git commit

My docker image requires git to be installed for npm to grab it which increases the size of image 😄 

```
133  requestOne(subject: string, msg: string | Buffer, options?: SubscribeOptions, timeout: number, callback?:Function) : number
                                                                                   ~~~~~~~

node_modules/nats/index.d.ts(133,80): error TS1016: A required parameter cannot follow an optional parameter.
```

Typescript wont compile my project because of this error, which is already fixed

**Comment by aricart** [comment]
@imatefx Done!
