### ISSUE TITLE
Client.connected not found in type definition

### ISSUE THREAD

**Issue by vertti** [nats-io/node-nats#134]
The field `Client.connected` is not included in the Typescript type definition file so it can't be correctly used from Typescript code.

**Comment by aricart** [comment]
Client is a events.EventEmitter, you get 'connect' and 'reconnect' events. The internal flag is an implementation detail.

**Comment by aricart** [comment]
The typescript program would looks something like this:
```
/// <reference path="./node_modules/nats/index.d.ts" />
import * as NATS from "nats";

var nats = require ('nats').connect();
nats.on('connect', function(arg) {
  console.log('connect', arg);
});

nats.on('reconnect', function(arg) {
  console.log('reconnect', arg);
});
```

The generated javascript (same a hand-coded with the exception of the `exports` line.
```
"use strict";
exports.__esModule = true;
var nats = require('nats').connect();
nats.on('connect', function (arg) {
    console.log('connect', arg);
});
nats.on('reconnect', function (arg) {
    console.log('reconnect', arg);
});
```
