### ISSUE TITLE
Be able to get the subject on buffer mode

### ISSUE THREAD

**Issue by jjp91** [nats-io/node-nats#138]
Hello,

When we open a wild card subscription, it would be intresting (in order to select the accurate API) to get the full subject inside the actual object provided, something like this  - {type:"buffer",data:[msg],subject:"fullsubject"}

Thank you by advance.

**Comment by derekcollison** [comment]
It does already.

https://github.com/nats-io/node-nats/blob/master/test/basics.js#L186
