### ISSUE TITLE
node-nats browser version?

### ISSUE THREAD

**Issue by antonioaguilar** [nats-io/node-nats#139]
Is there a way to convert ```node-nats``` to a browser version?

I have tried with ```browserify```:
```
 browserify lib/nats.js -o bundle.js
```

but this doesn't export the NATS methods properly.  Any idea on what I might be missing?

**Comment by aricart** [comment]
@antonioaguilar unfortunately NATS uses it's own tcp protocol. So you cannot use it directly from a browser as browsers only do HTTP/S or Websocket. 

This means that you'll need a websocket to tcp proxy, and a library such as
https://www.npmjs.com/package/websocket-nats.

**Comment by cgebe** [comment]
In face of NATS version 2 and the planned websocket connectivity, is there also a desire to implement the appropriate client functionality in this repo for browser usage?

Right now, we use https://github.com/isobit/websocket-nats , however it is not maintained anymore (we had to change stuff of this client in the past already). Especially due to the fact that we are switching to the new authentication mechanism of NATS 2.0 we would need to adjust.

Thank you!

**Comment by aricart** [comment]
The idea is a different repo.  We have an implementation that is waiting on direct websocket support from the server. The API is almost identical to the nats.ts client.

**Comment by cgebe** [comment]
That's great! Thank you very much, appreciate your work!

**Comment by oliverhausler** [comment]
@aricart https://github.com/isobit/websocket-nats says "Copyright (c) 2011-2015 Derek Collison" so this repo seems to be from you guys somehow. What's the reason why it isn't part of the NATS system. Does it have drawbacks, are there hidden issues? Or only the fact that it requires a proxy?

You're talking about "direct websocket support from the server". Is there an ETA?

Would be cool if you could shed some light.

**Comment by derekcollison** [comment]
The copyright was copied but this is not our work. We understand the community is looking forward to ws support and we plan on providing that support, hopefully this year. There are third party alternatives, as the one you highlighted, that can be used today with a proxy of some sort.

**Comment by oliverhausler** [comment]
@derekcollison Thanks. I don't see a repo yet, so commenting here:

When you add ws support to the server, it would be very useful if there was an auth handler for accepting cookies. Problem with web is that any auth token can be stolen, but the cookie is sent by the browser so harder to fake.

Note that the cookie cannot be used for identifying the connection as there may be multiple browser tabs sending the same cookie. But the cookie can be used to auth the client.

**Comment by derekcollison** [comment]
Security for webclients will be something we need to sort out for sure. NATS 2.0 has done away with username and passwords but the web is still not there for the most part.

**Comment by oliverhausler** [comment]
Problem seems to be that cookies are not sent by some browsers over wss. Also, CORS is an issue here. What we do is our clients make a REST call where the server receives the cookie and authenticates the client [could be `nats-account-server`]. Server returns a time-limited JWT which we use in wss as query param. Avoids CORS and lets the server pre-check the JWT **before** the actual socket is established (checking after establishing the socket would make it easy to DOS the server, so auth should happen as early as possible).

These are my 2 cents. Code is in Java, so I can't help with that.

**Comment by derekcollison** [comment]
Thanks!
