### ISSUE TITLE
Does nats follows SemVer?

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#140]
When yes please upgrade to 1.0.0 according to http://semver.org/#how-do-i-know-when-to-release-100.
When not what's the version strategy?

**Comment by aricart** [comment]
How can an API be 1.0 when the server itself isn't 
;)

**Comment by StarpTech** [comment]
@aricart because you maintain an abstraction of the api with a fixed interface. When the server api will change I don't think it has an impact of the api of the drivers. The version should mirror the state of the software.

**Comment by aricart** [comment]
True, but I think there should be some mapping. Otherwise when there are protocol changes it is difficult to mentally map what version of the client matches the server.
