### ISSUE TITLE
Add jslinter to Travis

### ISSUE THREAD

**Issue by petemiron** [nats-io/node-nats#144]
Add a linter (JSHint or ESLint) to travis builds to ensure consistent formatting and prevent common issues.

cc @kozlovic

**Comment by aricart** [comment]
@petemiron @kozlovic We actually do run a linter however formatting is not part of it.
I was thinking that likely we should use `jscs` - perhaps moving from jshint to eslint.
One thing is that changing the formatting will basically we'll dump all the blames on the file.

Also it we should pick some sort of style. I would go for https://github.com/jscs-dev/node-jscs/blob/master/presets/crockford.json, but realize that this will have significant changes on the code formatting, including variable declarations etc. Suggestions welcomed.

**Comment by kozlovic** [comment]
That's something I love about Go is that the formatting is no subjective ;-)
I don't know if we need a tool or not, or just simply manually fixing the obvious ones such as the one where adding code for INFO protocol. In other words, when adding or updating some code, take the opportunity to fix the formatting.

**Comment by StarpTech** [comment]
I vote for https://standards.com
