### ISSUE TITLE
TLS not automatically set to true when NATS.connect("tls://...")

### ISSUE THREAD

**Issue by petemiron** [nats-io/node-nats#148]
To keep consistency with the go client and simplify client configuration, the client should automatically set `tls=true` when `tls://` is specified in the URL connect string.

**Comment by sateffen** [comment]
This is already solved [in the code](https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L365) by [this commit](https://github.com/nats-io/node-nats/commit/2808452ea6264300b5353f8f92eced431b9c5df3), so this issue should be closed I guess.

**Comment by aricart** [comment]
@sateffen thanks
