### ISSUE TITLE
Issue connecting to nats service when NICs are disabled

### ISSUE THREAD

**Issue by Vonnguru** [nats-io/node-nats#152]
We think we are seeing this in a couple different configurations but basically if NICs are disabled or internet is not available, our node client cannot connect to our server. 

Has anyone seen this before? We are just using the default localhost for the url.

NatsError: Could not connect to server: Error: getaddrinfo ENOENT

**Comment by aricart** [comment]
What happens if you use an URL like `nats://127.0.0.1:4333`?
What OS is this? 

Local host must be resolved by dns.  What does your /etc/hosts and /etc/host.conf look like?

**Comment by aricart** [comment]
@Vonnguru  I haven't seen any more activity on this. This looks like the same issue as described here:
https://stackoverflow.com/questions/15527775/getaddrinfo-enoent-error-from-http-request-on-node-js

If you have different findings, please reopen this issue.

**Comment by Vonnguru** [comment]
Thank you - your answer was correct!
