### ISSUE TITLE
How can i run example on nodejs?

### ISSUE THREAD

**Issue by thanhngvpt** [nats-io/node-nats#153]
Hi all.
I'm following this page to start with nats http://www.nats.io/documentation/tutorials/nats-queueing/
on part 2 with command 
`
cd node_modules/nats/examples
node node-sub.js foo my-queue
`
I don't know where folder to run this command. Please help me out.
Thanks.

**Comment by aricart** [comment]
@thanhngvpt the examples are not part of the binary distribution installed by npm. To get the examples you need to clone the repo. https://github.com/nats-io/node-nats. The examples are in the 'examples' directory.

However more direct to your question, the documentation you list is wrong is saying that the node-sub.js allows a queue name argument (I have filed a defect on the documentation). You can easily modify the sample as per https://github.com/nats-io/node-nats#queue-groups.

Alternatively you can download the go samples from t https://github.com/nats-io/go-nats-examples. Also note that you will need to use https://github.com/nats-io/go-nats-examples/tree/master/nats-qsub to subscribe to a queue.
