### ISSUE TITLE
typings for tls don't allow tls options (object)

### ISSUE THREAD

**Issue by sittingbool** [nats-io/node-nats#155]
Hi for my test server I am using ClientOptions in the form of:
`{
    user: 'myuser',
    pass: 'mypass',
    tls: {
          rejectUnauthorized: false
    }
}`

 and I am using TypeScript. Without manually changing Typescript gives me an error because tls only accepts a boolean. Can you add `| Object` at least?

**Comment by aricart** [comment]
Hi @sittingbool can you have a look at this PR and verify that it works for you.
https://github.com/nats-io/node-nats/pull/156
Thanks!

**Comment by sittingbool** [comment]
Works fine for me, thats how i changed it manually in my node_modules and it compiled. Thanks!
