### ISSUE TITLE
Problem when subject contains space

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#158]
If subject of a publish contains space, then the second token will be treated as replyId, which is weired.

If subject cannot contains space, it should throw error as soon as possible

**Comment by aricart** [comment]
@zhaoyao91 - Yes if you have a single space on the subject and don't specify a reply inbox, the client will create a protocol message that behaves exactly as you describe:

`PUB <subject> [reply-to] <#bytes>\r\n[payload]\r\n`

The protocol separates the subject from the reply-to by a space.

We currently don't validate spaces on a subject on any of the clients, so this type of issue will be visible at the very least in go and node.

Just in case, the way to debug this type of issue where you are publishing a message, but are not receiving it, is to create a subscriber on ">", you can even use `nats-sub` to see this, as the subscriber will report the subject on which the message was received.

You can also write a simple test like 
https://gist.github.com/aricart/4c0dab586abf77eddcf6ed490e746c59.js
which will show the subject/reply-to and message payload.
