### ISSUE TITLE
Reconnection problem

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#159]
What's the default reconnection policy of this package? How could I config it?

In my cluster I encountered such problem several times, it seems services already disconnected from the server, or didn't connect at first time at all, but it just keeps running with a dumb nats and doesn't recover  event the nats server has already started.

**Comment by aricart** [comment]
@zhaoyao91  by default the client will attempt to reconnect 10 times waiting to seconds between connects. After that the connection will close. I have updated the readme with a small sample in the 'advanced usage'. See https://github.com/nats-io/node-nats#advanced-usage
