### ISSUE TITLE
Support gzip?

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#161]
Does this module support using gzip to compress the msg?

**Comment by aricart** [comment]
Not directly. You will have to create a zlib object and compress/decompress
the payload yourself as that is application specific encoding.

**Comment by zhaoyao91** [comment]
I noticed this sdk transfer **string** message, not buffer, does that mean I should base64 my gzipped data?

**Comment by tutman96** [comment]
If you set the option preserveBuffers you should be able to pass a Buffer in as the payload (and get them raw back)

**Comment by zhaoyao91** [comment]
thanks
