### ISSUE TITLE
Application can't resolve NATS dependecies

### ISSUE THREAD

**Issue by veznidav** [nats-io/node-nats#172]
I installed NATS via npm (npm install nats). Then followed basic usage. When I start the application I got this errors: 

`ERROR in ./node_modules/nats/lib/nats.js
Module not found: Error: Can't resolve 'net' in 'C:\p4\Mycore\Ui\main\Mycronic.Mycore.Ui.Loading\node_modules\nats\lib'
 @ ./node_modules/nats/lib/nats.js 14:10-24
 @ ./node_modules/nats/index.js
 @ ./ClientApp/boot-client.tsx
 @ multi react-hot-loader/patch event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot-client.tsx`

`ERROR in ./node_modules/nats/lib/nats.js
Module not found: Error: Can't resolve 'tls' in 'C:\p4\Mycore\Ui\main\Mycronic.Mycore.Ui.Loading\node_modules\nats\lib'
 @ ./node_modules/nats/lib/nats.js 15:10-24
 @ ./node_modules/nats/index.js
 @ ./ClientApp/boot-client.tsx
 @ multi react-hot-loader/patch event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot-client.tsx`

Any help?

**Comment by aricart** [comment]
Are you trying to use it inside of a web project?

**Comment by veznidav** [comment]
I am trying to use it in a web browser. Is there any opportunity how to use nats in a browser? I need it for receiving push notifications from the server.

**Comment by aricart** [comment]
You would have to have a layer to do websockets. 
Take a look at https://github.com/isobit/websocket-nats,

**Comment by veznidav** [comment]
You are right, thank you. One more question - is there any simpler way, how to make a client browser just receiving the nats messages?

**Comment by aricart** [comment]
Unfortunately not yet.
