### ISSUE TITLE
Queueing Semantics

### ISSUE THREAD

**Issue by abacaj** [nats-io/node-nats#177]
Hi, I assume when we say 'queueing' we are enqueuing messages to the queue that will be dequeued when a client is subscribed.

If there are no subscribers it seems that the 'queue' doesn't exist at all, the publisher publishes messages to some queue but when I start the subscriber there is no dequeuing happening and only when the publisher + subscriber are connected does this 'queue' exist. 

This doesn't seem to represent what I thought was a queueing mechanism, seems more like a direct connection to the subscriber.

The benefit of a queue is that messages can build up and subscribers can join to dequeue faster, am I missing something? What is the benefit in this case where the queue doesn't build up but is a direct connection? What if all subscribers crash, then the queue is gone?

Thanks!

**Comment by aricart** [comment]
On NATS a subscriber queue is really a group of subscribers that load balances a subscription under a given 'queue' name. The server selects a subscriber between members of the subscriber queue to which to send the published message. There's no persistence provided by NATS, so if messages are published when no subscriber is available, it is simply discarded. 

For persistence, you need to look at [nats-streaming-server](https://github.com/nats-io/nats-streaming-server) and [node-nats-streaming](https://github.com/nats-io/node-nats-streaming)
