### ISSUE TITLE
How to promisify nats.subscribe

### ISSUE THREAD

**Issue by ilyjs** [nats-io/node-nats#182]
```
const {promisify} = require('util');
let NATS = require('nats');
let nats = NATS.connect("http://0.0.0.0:4222");
let subscribe = promisify(nats.subscribe);

 await subscribe('foo')
         .then(msg => ctx.body = msg)

```
erorr :

> Cannot read property 'closed' of undefined TypeError: Cannot read property 'closed' of undefined
>     at Client.subscribe (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/nats/lib/nats.js:1139:14)
>     at tryCatcher (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/bluebird/js/release/util.js:16:23)
>     at ret (eval at makeNodePromisifiedEval (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
>     at router.post (/Users/netkacila/Documents/projects/oko_front/simple_api/api/index.js:261:12)
>     at dispatch (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
>     at next (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
>     at /Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/lib/router.js:345:16
>     at dispatch (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
>     at /Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
>     at dispatch (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-router/lib/router.js:350:31)
>     at dispatch (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-compose/index.js:42:32)
>     at next (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-compose/index.js:43:18)
>     at createGenerator (/Users/netkacila/Documents/projects/oko_front/simple_api/api/node_modules/koa-convert/index.js:24:16)
>     at createGenerator.next (<anonymous>)
>     at Object.<anonymous> (/Users/netkacila/Documents/projects/oko_front/simple_api/api/handlers/08-multipartParser.js:14:5)
>     at Generator.next (<anonymous>)
>

**Comment by aricart** [comment]
node-nats at this time cannot be promisified. As per [promisify](http://bluebirdjs.com/docs/api/promise.promisify.html) docs:

> The node function should conform to node.js convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.

**Comment by ilyjs** [comment]
**aricart  thanks for your reply!**

> It works for me :


```
let promise =  new Promise((resolve, reject) => {
        nats.subscribe('foo',function(msg) {
            resolve(msg)
        } )
    })

 await promise.then( msg => ctx.body = msg )
```
