### ISSUE TITLE
Queue groups don't work because of not unique ssid

### ISSUE THREAD

**Issue by grbr** [nats-io/node-nats#188]
Hello,

I wanna run a few copies of client in cluster. And i can not ensure the uniqueness of the subscription's id because the id is generated sequentially inside the library.

[https://nats.io/documentation/internals/nats-protocol/](url)
> SUB <subject> [queue group] <sid>\r\n
> sid: A unique alphanumeric subscription ID

It's unique only in same instance of node-nats.
`this.ssid += 1;`
Can you replace this with some guid, uuid or anything everywhere-unique

**Comment by grbr** [comment]
Sorry, issue was in my client code. Everything work fine now.

**Comment by derekcollison** [comment]
SID (Subscription IDs) are closures under a single connection. There uniqueness only has to be within the context of that connection.
