### ISSUE TITLE
Cannot Specify External Connection

### ISSUE THREAD

**Issue by dlabey** [nats-io/node-nats#19]
When I try to do:
```
nats.connect({
    url: '127.0.0.1',
    port: '4222'
  });
```

I get:
```
TypeError: port should be a number or string: null
    at Socket.connect (net.js:914:13)
    at Object.exports.connect.exports.createConnection (net.js:92:35)
```

It looks like there is no default for opts.port and opts.port is not being assigned as an option.

**Comment by derekcollison** [comment]
You are not pasing a url, you are passing an IP which when parsed by url.Parse can not find a scheme or protocol and hence no default port. I can add code to pull the port option in, but it's best to do the following.

```js
nats.connect('nats://127.0.0.1:4222');
```

**Comment by dlabey** [comment]
Will this work for Consul as well?

**Comment by ajschlosser** [comment]
@dlabey ```'nats://your-favorite.consul.service:4222'``` will work.

**Comment by dlabey** [comment]
Ah yes worked well.
