### ISSUE TITLE
Subscription is canceled although expected msg count is null or negative

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#201]
Hi, the current timeout implementation does not allow to use only the timeout feature without to specify a count of expected messages.

**Use case:**
The user should be able to receive max N messages or less. In this case, he is responsible to close the INBOX before it happens automatically (max-messages, timeout, expectedMsg).

nats: 0.8.2

```js
var NATS = require('nats')
var nats = NATS.connect()

// Replies
nats.subscribe('help', function(request, replyTo) {
  nats.publish(replyTo, 'I can help!')
  nats.publish(replyTo, 'I can help!')
  nats.publish(replyTo, 'I can help!')
  nats.publish(replyTo, 'I can help!')
  nats.publish(replyTo, 'I can help!')
})

var sid = nats.request('help', null, { max: 5 }, function(response) {
  console.log('Got a response for help: ' + response)
})

// Timeout unless a certain number of messages have been received
nats.timeout(sid, 2000, null, function() {
  console.log("timeout")
})
```

## Output
```
Got a response for help: I can help!
```
## Exptected Output
```
Got a response for help: I can help!
Got a response for help: I can help!
Got a response for help: I can help!
Got a response for help: I can help!
Got a response for help: I can help!
```
## Solution:
Only assign the value to the property [here](https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L1312) when the value of `expected` was set explicit. I can create a PR.

**Comment by aricart** [comment]
Hi @StarpTech timeout has always been associated with a message count for a subscription, and one of two things happens. Either you get the message count within the allotted time or the timeout fires. When the max number of messages is specified on a request or subscription, the library will auto-unsubscribe you when that count happens (ie by the time you get invoked in your callback, the unsubscribe already happened). This is not related to the timeout functionality, but rather on a subscription option (which can be set by the timeout).

I think your use-case is to subscribe and get as many messages as you can in a specified period of time. If this is the case, this is a very specific use-case, which you can easily implement yourself on your code.

**Comment by StarpTech** [comment]
Hi @aricart this sounds reasonable to me. Thanks for the clarification.
