### ISSUE TITLE
Add reply, subject and sid to respmux callback invocation

### ISSUE THREAD

**Issue by omg** [nats-io/node-nats#204]
Are reply, subject and sid args deliberately missing here and can they be added back plz?
https://github.com/nats-io/node-nats/blob/4079c2b928e0ee36566c3e3e2724b40c1bb4665f/lib/nats.js#L1474

I propose this way of invocation:
`conf.callback(msg, reply, subject, conf.id)`
to keep it compatible with subscription and "old" request callbacks

**Comment by aricart** [comment]
@omg thanks for the catch. The original implementation of request simply gave the message and the possible reply subject. Not quite sure if the additional arguments are useful, the subject certainly shouldn't be used, as the handler for those messages could be dropped and are internally generated.

**Comment by aricart** [comment]
@omg  this is fixed in v0.8.4

**Comment by omg** [comment]
@aricart  Thank you, reply is sufficient for me. But "sid" arg can actually be useful when you have custom unsubscription logic other than max or timeout (by sid i mean here mux id, not actual subscription id). Subject may not be of much use but could be there for the sake of callback signature uniformity

**Comment by aricart** [comment]
@omg, the real issue is whether we are doing a 'subscription' or a convenience request api call. I think one shouldn't require management. Only reason why I didn't add the other arguments is that the old implementation didn't provide them.
