### ISSUE TITLE
async await api?

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#208]
Could you please offer async/await version of for subscribe and publish/request ?

**Comment by aricart** [comment]
@zhaoyao91 we currently are constrained by node v4 capabilities. We are considering a version of the library that is transpiled for the different runtimes. This would  allowing clients and library developers work using current ECMAScript, but continue to target whatever runtime version they require.

**Comment by JannikZed** [comment]
any news on this issue?

**Comment by aricart** [comment]
@JannikZed take a look at https://github.com/nats-io/ts-nats

Cheers
