### ISSUE TITLE
on('close') will never get called

### ISSUE THREAD

**Issue by zhaoyao91** [nats-io/node-nats#210]
due to https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L634

the on('close', handler) will not get called.

**Comment by zhaoyao91** [comment]
more, call `nats.close` will cause app exit without any error. I don't know why.

**Comment by aricart** [comment]
@zhaoyao91 `on('close`) is only emitted when the connection the server is closed. Not when client code calls `close()`.
