### ISSUE TITLE
0.8.6: TypeError: Cannot read property 'pingTimer' of undefined

### ISSUE THREAD

**Issue by zpr** [nats-io/node-nats#214]
node_modules/nats/lib/nats.js:641:13

**Comment by aricart** [comment]
@zpr  what version of the library?
In master the code looks valid.

**Comment by aricart** [comment]
@zpr - Please attach a stack trace. Thanks.

**Comment by zpr** [comment]
Just downloaded the master as the npm version is 0.8.4 not 0.8.6. Same issue in both.

TypeError: Cannot read property 'pingTimer' of undefined
    at Client.close (node_modules/nats/lib/nats.js:641:13)
    at Timeout._onTimeout (node_modules/nats/lib/nats.js:1355:13)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

node -v
v9.5.0

**Comment by aricart** [comment]
@zpr - Not quite sure how you are getting to close() when the client is null. Can you show me callbacks where you are calling `close()`.

**Comment by aricart** [comment]
@zpr - No replies to the queries, so I am assuming the issue is resolved. If not please reopen and provided the requested information. Thanks.
