### ISSUE TITLE
Create subscription object like in node-nats-streaming, go-nats

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nats#218]
As titled. This is much more developer friendly than to register and listen on global events.

This abstraction is already in use in [`go-nats`](https://github.com/nats-io/go-nats/blob/master/nats.go#L319) and [`node-nats-streaming`](https://github.com/nats-io/node-nats-streaming/blob/master/lib/stan.js#L574).
```js
const sub = nats.subscribe('help', function(request, replyTo) {
  nats.publish(replyTo, 'I can help!');
});
sub.once('unsubscribed', () => {
	// some code
})
sub.unsubscribe()
```
vs 
```js
const subId = nats.subscribe('help', function(request, replyTo) {
  nats.publish(replyTo, 'I can help!');
});
nats.on('unsubscribed', (sid, subject) => {
	if (sid === subId) {
		// some code 
	}
})
nats.unsubscribe(subId);
```

**Comment by aricart** [comment]
@StarpTech  - Thanks for the suggestion. Already working on a more modern client. Will incorporate feedback.

**Comment by StarpTech** [comment]
@aricart possible to track your progress?

**Comment by aricart** [comment]
Not yet.

**Comment by StarpTech** [comment]
What's the status of your work?

**Comment by aricart** [comment]
This is fixed in ts-nats, a version of the library that provides support for more modern javascript.
