### ISSUE TITLE
use cuid for createInbox

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#22]
The `createInbox` implementation is a bit inefficient both in terms of size and uniqueness, I would suggest a much better implementation such as https://github.com/ericelliott/cuid.

**Comment by derekcollison** [comment]
Thanks I will take a look..

**Comment by ronag** [comment]
I'm not sure but I believe, especially depending on the javascript engine, using only Math.random for unique id generation makes it not entirely unlikely to get collisions.

**Comment by derekcollison** [comment]
True depends on entropy pool underlying. Thanks again for all feedback on Node.js client. Will get these issues taken care of..

**Comment by derekcollison** [comment]
FYI, working on nuid() version for Node.js. But did benchmark current implementation, which I agree is not too great, against cuid.

```
~/Development/go/src/github.com/nats-io/node-nats/benchmark> node -v
v5.7.0

~/Development/go/src/github.com/nats-io/node-nats/benchmark> node cuid_perf.js 
cuid() Performance Test
130301/sec

~/Development/go/src/github.com/nats-io/node-nats/benchmark> node inbox_perf.js 
createInbox() Performance Test
205782/sec
```

**Comment by ronag** [comment]
@derekcollison: One faster way would be to have a pool of ids. Since you know when the inbox is no longer used old ids can be re-used.

**Comment by derekcollison** [comment]
I think nuid approach will work well and avoid collisions with other clients vs reuse pool.

**Comment by ronag** [comment]
@derekcollison: :+1:
