### ISSUE TITLE
tls 

### ISSUE THREAD

**Issue by zhangjian326** [nats-io/node-nats#221]
hi the tls must 1024 ? i make 512 is don.t work

**Comment by zhangjian326** [comment]
the client is error 
Could not connect to server: Error: write EPROTO 101057795:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:openssl\ssl\s3_pkt.c:1487:SSL alert number 40
101057795:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:openssl\ssl\s23_lib.c:177:

**Comment by aricart** [comment]
@zhangjian326 - yes node is not happy with 512 bit keys even if the go clients are. Many have deactivated support for RSA and DSA keys that are shorter than 1024.  When testing the go client, it reported connecting with the  `ecdhe-rsa-aes128-gcm-sha256` cypher. This cypher is available on node.
