### ISSUE TITLE
TLS Incompatible with Node 10

### ISSUE THREAD

**Issue by Cherry** [nats-io/node-nats#222]
After updating to Node 10, we're seeing the following error when attempting to connect.

``` NatsError: Could not connect to server: Error: write EPROTO 15860:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:210:```

I imagine this is likely due to the OpenSSL update in Node 10?

**Comment by aricart** [comment]
Tried the following:

- setting the node flag `--tls-cipher-list` to the list of default ciphers `ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256`

- changing the `secureProtocol` option to all the various options

- changing `secureOptions` and to turn off SSLv3 in case that was the problem

- setting `ciphers` directly on the tls options

No success on any of these things. May need to sit tight until further burn-in is reported on node 10.

**Comment by Cherry** [comment]
@aricart Thanks for your work resolving this! Can this be marked as resolved now as of https://github.com/nats-io/node-nats/commit/a29570db32ed5cc90d2107851cc8e88ff255e685?

**Comment by aricart** [comment]
@Cherry yes - but note the new node requirement - you have to be 4.5 or greater! - no release yet... Working on it.

**Comment by Cherry** [comment]
Any ETA on a release for this? We'd love to bump our infrastructure to Node 10.

**Comment by the-nose-knows** [comment]
So what are we supposed to use in the meantime for the latest & greatest Node that actually supports TLS, @aricart ?

**Comment by KClough** [comment]
FYI I'm seeing this same issue with Node 8.12.0

**Comment by jeffrichiefs** [comment]
@aricart why is this ticket closed?

**Comment by aricart** [comment]
@jeffrichiefs @KClough @the-nose-knows - can you be more specific of the problems you are having. The current version of node-nats and gnatsd are passing with https://travis-ci.org/nats-io/node-nats/builds/428650560 (just ran them on my system with v8.12.0 and v10.13.0. What gnatsd versions are you matching against?

**Comment by aricart** [comment]
Also make sure your keys are bigger than 512. See https://github.com/nats-io/node-nats/issues/221

**Comment by praveen0051** [comment]
Add only http proxy and this would solve the issue. Tls handshake seems the cause
