### ISSUE TITLE
Support for TLS termination at load balancer

### ISSUE THREAD

**Issue by doubliez** [nats-io/node-nats#232]
I'm experimenting with NATS and have set up gnatsd to run with TLS disabled behind an AWS ELB which does TLS termination.

It seems node-nats doesn't support this setup as it first opens a socket connection to the server, and initiates a TLS connection only if the server replies with `tls_required: true` in the INFO message.

I'm sure there's a reason why it has been implemented like that (I'm not that familiar with NATS yet), but shouldn't the client directly initiate a TLS connection when the `tls: true` option is passed? This would fix my problem.

In the code I tried replacing the following line:
```javascript
this.stream = net.createConnection(this.url.port, this.url.hostname);
```
by:
```javascript
this.stream = tls.connect({
    host: this.url.hostname,
    port: this.url.port
});
```
and it connects fine, provided I disable the TLS mismatch check (since the client sets `tls: true` but the server will send `tls_required: false`).

Is it something that would be possible to support? Or should I just look into configuring TLS in gnatsd instead of at the ELB level (which would be a bit annoying)?

**Comment by aricart** [comment]
@doubliez the NATS server does its initial connection as non-TLS and then upgrades. This is an issue with the server - see https://github.com/nats-io/gnatsd/issues/291

Effectively until the server supports it, you cannot use an ELB to load balance TLS configured servers.
