### ISSUE TITLE
Message stream broken on error in callback

### ISSUE THREAD

**Issue by valichek** [nats-io/node-nats#233]
Exception thrown in callback will break all the following messages. The reason is that execution will stop at this line: https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L971, `client.pstate` will never changed and parsing of `client.inbound` will break.

**Comment by StarpTech** [comment]
That's the typical behavior of synchronous errors in Node.js you have to `try/catch` it.

**Comment by valichek** [comment]
@StarpTech sure it's typical, but the library is async, so I would try call callbacks async as well, maybe `setImmediate()` could be used here https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L1093 to fix this problem.

**Comment by StarpTech** [comment]
I think I don't understand your case. Could you make a repro? Snippet?

**Comment by valichek** [comment]
@StarpTech smth like
```
nats.subscribe('help', function(request, replyTo) {
  throw new Error('this error will break all subsequent received messages')
});
```

**Comment by StarpTech** [comment]
As I expected this can't be fixed. You have to catch the error. It's by design that the lib doesn't catch the error for you.

**Comment by valichek** [comment]
well, if using `setImmediate()` is not somehow a solution here, this should be documented, but it's really weird that one exception can break everything and be even harmful for the data

**Comment by StarpTech** [comment]
What do you expect from `setImmediate()`? It will postpone the execution but will still throw the error asynchronously. It's your responsibility to write save code.

```js
nats.subscribe('help', function(request, replyTo) {
  try {
  	opThatCanThrow()
  } catch(err) {
	logStuff(err)
  }
});
```

**Comment by StarpTech** [comment]
@valichek For better understanding https://hemerajs.github.io/hemera/docs/error-handling.html

**Comment by valichek** [comment]
@StarpTech the problem is not to catch error, problem is that not catched error will influence to all the received data and subscriptions. What if I don't want to catch it? This can be the case as well. This error will produce errors in other callbacks and it will be really hard to track the reason.

**Comment by kozlovic** [comment]
I don't know enough Node.js to have a valuable input, but unless in Node if the library were to catch the error it would prevent the user to catch it, then the library should catch any error to prevent misbehaving user callback to cause the library to fail.

**Comment by aricart** [comment]
@valichek if you don't catch the error the correct thing is for the library to fail. In the case of your subscription, the error may indicate that you were unable to process the message, how should the library interpret your error or exception? It really cannot recover for you because your intention may be to have the process fail or to continue, either excludes the other.

Effectively the problem is that messages that are already in flight could be lost by the client failing, but NATS doesn't ensure that you receive messages. If you really want some component to know you didn't drop a message you must send a request, and only when your reply is sent can that component know that the message has properly handled.

**Comment by kozlovic** [comment]
@aricart I disagree.

**Comment by aricart** [comment]
@valichek the only other possible solution is for me to catch the exception on your handler, and then send it right back to you via the error handler.

**Comment by StarpTech** [comment]
@valicheck I understand your point but it's the same as with everything in Node.js e.g if you create multiple endpoints in express and you throw an error inside one your server will exit. That's the nature of the limited isolation.

**Comment by valichek** [comment]
@aricart the problem here is that not just in-flight messages lost on error, all subsequent messages got by client will not be correctly parsed because `inbound` buffer is no longer valid after uncaught error

**Comment by aricart** [comment]
@valichek agreed - the fix that I have put should address the problem by notifying you timely that an error happened, and not corrupting the processing of subsequent messages.

A bit of background: 

 `processMsg` is called from a loop and the inbound buffer usually gets messages in batches. This means that the event loop will not return until the inbound buffer is fully drained, or the `yieldTime` option has exceeded the maximum amount of time desired for messages processing.

For the reasons explained above, any scheduled `setImmediate` will not happen until the inbound buffer has fully drained which is likely way in the future from where the error occurred.

On the fix I am proposing, by emitting `error` at least I am notifying you that an error happened synchronously right when the error happens. At that point, it is up to you to evaluate the exception and decide what to do.

**Comment by valichek** [comment]
@aricart yes, this is true about draining of the buffer, is it really a problem? is execution of callbacks supposed to be async or sync? currently execution of a callback depends on time of processing the previous message, looks a bit confusing, even if we assume that there are no real concurrency in node, anyway one can always wrap callbacks with `setImmediate()`

**Comment by aricart** [comment]
Yes depending on the messages you effectively would continue processing and scheduling. On busy clients, I would not be surprised to see OOM or some other similar type of error.
