### ISSUE TITLE
Unable to connect to port `4222`  with Docker

### ISSUE THREAD

**Issue by RameshRM** [nats-io/node-nats#243]
Unable to connect to `nats server` running on docker with `localhost`

Monitoring port is running `http://localhost:8222` but not able to connect to port `4222` from another docker container , Any pointers?

**Comment by RameshRM** [comment]
Example Code from the Container 

```javascript
'use strict';

const WAIT = 'wait';
const READY = 'ready';

module.exports.getConnection = tryGetConnection();

const Nats = require('nats');

function tryGetConnection() {
  let _client;
  return function(next) {
    if (!_client) {
      _client = Nats.connect({
        'url': "nats://0.0.0.0:4222"
      });
      bindEvents(_client);
    }
    return next(undefined, _client);
  }
}


function bindEvents(connection) {
  let status;
  connection.on('error', function onErr(e) {
    status = WAIT;
    console.log('NATS: Connect Err', e);
  });

  connection.on('close', function onClose() {
    status = WAIT;
    console.log('NATS: Closed');
  });

  connection.on('connect', function(cn) {
    status = READY;
    console.log('NATS: Connected');
  });

  connection.on('disconnect', function() {
    status = WAIT;
    console.log('NATS: Disconnected');
  });

  connection.on('reconnecting', function() {
    status = WAIT;
  });

  connection.on('reconnect', function(nc) {
    status = READY;
  });
}


tryGetConnection().call(this, function(err, result) {

});

```

**Comment by aricart** [comment]
@RameshRM how are you running docker nats exactly, did you expose the ports to the host?
ie `docker run -p 4222:4222 -p 8222:8222 -ti nats:latest`

**Comment by RameshRM** [comment]
Yes, i am running same like ur `docker run`

**Comment by aricart** [comment]
For two containers to communicate, you are going to have to bridge their network stacks, take a look at: [https://docs.docker.com/network/bridge/](https://docs.docker.com/network/bridge/)

**Comment by sateffen** [comment]
The main problem is line 15 `'url': "nats://0.0.0.0:4222"` as connection URL, as you can't connect to a broadcast IP.

If your service should listen to all networks, you use `0.0.0.0` as bind-IP to listen on all networks, but when you want to connect to the corresponding server/container, you need to address it with its actual IP. As soon as you use the actual IP as connection URL, you'll be able to connect.
