### ISSUE TITLE
Port option overwritten by this.assignOption(opts, 'url')

### ISSUE THREAD

**Issue by witq** [nats-io/node-nats#244]
I noticed that the url generated if the port connection option is provided is immediately overwritten so in effect the port option is ignored. Is the port option deprecated? If not, I can submit a PR fixing this.

**Comment by aricart** [comment]
@witq This works for me:

```
        var nc = NATS.connect({port: 1424});
        nc.on('connect', function() {
            console.log("here")
            nc.close();
        });
```

Can you show me what other options you have in your connection?

**Comment by witq** [comment]
I'm actually using nats-streaming-server so it looks like this:
`
const stan = nss.connect('test-cluster', 'test-client', {
 port: 4223
});
`
I've noticed that nats-streaming-server does not pass this option to the nats client. I modified it to pass it and then noticed those few lines in nats.js:272:
`
if (opts.port !== undefined) {
            options.url = DEFAULT_PRE + opts.port;
        }
        // Pull out various options here
        this.assignOption(opts, 'url');
        this.assignOption(opts, 'uri', 'url');
`
First, options.url equals DEFAULT_PRE + the port I've set but then it's overwritten with the default url since opts contains the default url.
Maybe the issue is actualy in node-nats-streaming? 🤔

**Comment by aricart** [comment]
node-nats-streaming is filtering some of the options. The 'port' option is kind of a ninja because it is not specifically named - it is possible the streaming library is not exporting it. Let me check.

**Comment by aricart** [comment]
yes this is a node-nats-streaming issue.

**Comment by witq** [comment]
My debugging skills must have failed me then. I guess I'll give it another go and submit a PR to node-nats-streaming 👋

**Comment by aricart** [comment]
if you can open it, that would be awesome. I have a branch you can test.

**Comment by aricart** [comment]
this is now fixed master on node-nats-streaming.
