### ISSUE TITLE
node-nats vs ts-node

### ISSUE THREAD

**Issue by sateffen** [nats-io/node-nats#245]
Hey,

I've got a question regarding this repository and [ts-nats](https://github.com/nats-io/ts-nats): Why are there 2 clients, that fulfill the same duty, for the same platform?

node-nats is basically a javascript client for node, while ts-nats is a typescript client for node, whereas typescript is transpiled to javascript. Now I'm a little confused, whether one of the clients is discontinued or what their relation is.

Maybe you could explain the future plans of the clients?

**Comment by StarpTech** [comment]
Answered here https://github.com/nats-io/ts-nats/issues/15

**Comment by aricart** [comment]
@sateffen thanks for the question. The typescript client is intended to expose a more modern JavaScript programming model. Also, the internals for the transport is pluggable which will allow other forthcoming implementations to work without requiring supporting a completely different client.

The idea is once the ts-nats client becomes more mature, to deprecate the node-nats client (or replace the internals of the node-nats client with the ts-implementation)

The ts-node client also provides similar client API to a not yet public client ws-client which is intended for the browser.

Additionally, if you use modern tooling to develop your software you will have a better experience in the process. This was all described in this blog post [https://nats.io/blog/ts-nats/](https://nats.io/blog/ts-nats/)
