### ISSUE TITLE
Support for SRV record types

### ISSUE THREAD

**Issue by howardengelhart** [nats-io/node-nats#248]
I ran into this when attempting to run a nats server in an ECS service using Host networking.  If you use the Service Discovery feature to publish the network address of the nats server so it can be reached by name from other ECS containers, AWS currently only supports SRV record types, which map host + port.  This appears to break the ability to configure a connection using this library.

The current workaround is to use AWSVPC networking, which allows the Service Discovery to create A or SRV records.   So not a critical issue, but certainly a nice-to-have.

**Comment by aricart** [comment]
Added an example on how to do this. I don't believe that this should be part of the API, but definetly some clients will want to have the code to augment a single nats url with resolution from A/AAA/SRV records.

FIX #252

**Comment by aricart** [comment]
See https://github.com/nats-io/node-nats/blob/master/examples/expander

**Comment by howardengelhart** [comment]
Thanks for the example @aricart.

**Comment by chongma** [comment]
I can't find the example

**Comment by aricart** [comment]
@chongma  Try, https://github.com/nats-io/nats.js/pull/252/files - note that the configuration of the client is a bit different, but the processing is outside of the nats client, you have to process the records, and then configure your nats client accordingly.

**Comment by chongma** [comment]
Thanks @aricart
