### ISSUE TITLE
Support for multiple IPs in a A/AAAA DNS record

### ISSUE THREAD

**Issue by arnulfojr** [nats-io/node-nats#249]
[Idea|Proposal]
So currently, nats uses the `net` package to create a TCP connection to the (NATS) server.
The current implementation basically takes the first IP from the domain name and uses it to create a TCP connection.
For users that can’t implement different loadbalancing techniques through the DNS, using the first IP from the record is kind of a bummer and kind of forces the servers to have multiple domains (as only the first IP is used).

What would be really cool, is that before or while creating the TCP connection to the server, the dns resolution returns all the IPs and uses them as nats server endpoints to connect, enabling reconnecting to all the IPs in the record.

Let me know what you guys think!

**Comment by derekcollison** [comment]
We do this for the Go client now so this will probably make sense.

**Comment by aricart** [comment]
See https://github.com/nats-io/node-nats/blob/master/examples/expander

**Comment by arnulfojr** [comment]
:D this does not seem like support from your side :D but thanks for the example tho!

**Comment by derekcollison** [comment]
Hey @aricart any reason we should not add this into base like we do with Go client?
