### ISSUE TITLE
Typings don't support publish(subject, message) call

### ISSUE THREAD

**Issue by shedar** [nats-io/node-nats#261]
Basic usage example is not supported by typings
```javascript
nats.publish('foo', 'Hello World!');
```

In the commit fixing #246, reply was made mandatory https://github.com/nats-io/node-nats/commit/70a055d993b2c0e2bd052cb7e3b732143871f138#diff-b52768974e6bc0faccb7d4b75b162c99R117 and thus it can't be applied to the above call

**Comment by derekcollison** [comment]
Thanks, I think this is a regression. @aricart will take a look.
