### ISSUE TITLE
port tokenHandler callback from go-nats

### ISSUE THREAD

**Issue by andriy-bulynko** [nats-io/node-nats#265]
In some use cases auth tokens might have expiry (like JWTs). In those cases, it would be nice to have a mechanism to ask for a new token before using it for authentication. `go-nats` already had that functionality added. It would be great to make `node-nats` feature compatible.

**Comment by aricart** [comment]
@andriy-bulynko thanks for the PR - one issue I see is we don't use Promises anywhere on node-nats. Also, if you look we seem to have an ever-growing number of options for providing authentication - with the upcoming 2.0 nkeys, jwts, credential files, etc, we have a lot of handlers. I am starting to think that really what we should do is provide a connection option that takes a function and returns a connection option. Then this way all options could be dynamically resolved at the time of the connect while simplifying the API for providing these.

**Comment by aricart** [comment]
@derekcollison wdyt?

**Comment by derekcollison** [comment]
We need to look at more proactive re-authentication.

The Go client will read in the credentials files (new NATS 2.0 style security) such that the connection can be reestablished with the new credentials just by updating the file, but the connection will still be dropped by the server. We will do this work post 2.0.

**Comment by aricart** [comment]
@derekcollison this is actually already implemented for the new authentication methods - jwt and creds, etc auto re-request the authentication configuration before connect.
A more general solution could be to allow clients to provide a function that return an auth options object that is refreshed for every connection.

**Comment by derekcollison** [comment]
@aricart yes I remember, I wrote it ;)

What I mean is we are not proactive about expirations.

**Comment by aricart** [comment]
lol

**Comment by andriy-bulynko** [comment]
@aricart: Some callback before the connection to refresh the credentials would be extremely useful. Also, where could I read up on the upcoming planned JWT support you alluded to? Currently, we are already using `tokens` to pass JWTs, which is why we need a mechanism to refresh them.. Thanks!

**Comment by aricart** [comment]
@andriy-bulynko the changes are on master and currently in production on our ngs service (see https://www.synadia.com/ngs).

You can read about some of the underlying tech in:
https://github.com/nats-io/jwt
https://github.com/nats-io/nkeys 
https://github.com/nats-io/nsc 

The nkey/jwt authentication effectively supersedes all the other mechanisms.
Docs and visibility of the functionality will show up in the next few days as we release for 2.0. Stay tuned!
