### ISSUE TITLE
Subscription Callback Invocations

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#28]
Shouldn't we protect subscription callback invocations in a try/catch? Right now if the user provided callback throws an exception the parsing state becomes broken.

**Comment by derekcollison** [comment]
I don't believe so, try/catch are expensive and I believe distributed systems should fail fast. A user can wrap a function with try/catch if they choose.

**Comment by ronag** [comment]
Hm, I didn't realise try/catch were expensive. Usually they are near zero overhead unless something is actually thrown. But yes, they seem to have a bit of an overhead in node.

**Comment by ronag** [comment]
again back to https://github.com/nats-io/node-nats/issues/32
