### ISSUE TITLE
Request subscription leak on invalid msg

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#29]
If a user passes in an invalid msg argument the publish function might throw an exception which will leave the subscription dangling. Request should probably look like this instead:

```
Client.prototype.request = function(subject, opt_msg, opt_options, callback) {
  if (typeof opt_msg === 'function') {
    callback = opt_msg;
    opt_msg = EMPTY;
    opt_options = null;
  }
  if (typeof opt_options === 'function') {
    callback = opt_options;
    opt_options = null;
  }
  var inbox = createInbox();
  this.publish(subject, opt_msg, inbox);
  return this.subscribe(inbox, opt_options, function(msg, reply) {
    callback(msg, reply);
  });
};
```

Also publish should probably assert that the `msg` is a string or explicitly try to convert it to a string since nothing else should work with `Buffer.byteLength`.

**Comment by derekcollison** [comment]
You need to subscribe before you publish. If not it's possible to have a race condition and miss the response since the subscription may not be processed yet.

**Comment by ronag** [comment]
I don't think you can get a response before the subscription since publish will have to dispatch the actual message asynchronously.

**Comment by derekcollison** [comment]
I can promise you it's possible. The server can process the PUB, send it to the responder and get a response back in a separate Go routine and throw it away before the SUB is received if its in a split buffer.

**Comment by derekcollison** [comment]
In terms of assuring the message is a string or convertible to one, again, not sure we should spend time within the client and should instead have Node.js fail fast on bad args.

**Comment by ronag** [comment]
You sure? The 'data' event should not be able to be invoked while still inside the `request` function. I don't see how the `processMsg` function could be called before subscribe.

I will have to give some more thought into your "fail fast" argument.

**Comment by ronag** [comment]
https://github.com/nats-io/node-nats/issues/32

**Comment by derekcollison** [comment]
It does not matter what the client is doing, if the server discards the message because the interest graph is not correct, doesn't matter what the client is doing will never receive the message.

**Comment by ronag** [comment]
Ah, of course. You are right. Thank you for explaining.

**Comment by derekcollison** [comment]
No problem at all.
