### ISSUE TITLE
Argument Validation?

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#32]
What is the policy in regards to argument validation? Right now a lot of weird stuff can quietly happen or crash the entire node process if users pass in invalid arguments, but maybe we leave the responsibility to the user?

**Comment by derekcollison** [comment]
Its Javascript, so I do some arg validation but in general the app should be responsible. Will look at PRs for additional arg validation, but will be critical if its in the fast path for publishing or message delivery.

**Comment by ronag** [comment]
Alright. We have a bit of a different policy internally (especially for NODE_ENV != 'production') but we can easily make a wrapper so that's fine.

**Comment by derekcollison** [comment]
It's a philosophy, but fail fast works in distributed systems IMO. I have written systems that try to recover, and I still do that to some degree in the server. For the client, it's more up to them the philosophy they want to take, but be good to watch "how much" a client is trying to recover, sometimes it's better to fail fast with error logs captured and restart.

**Comment by ronag** [comment]
Well, if there is a logic error recovering will not do much to help. There is a difference between a runtime error and a logic error. We want to catch or at least make logic and programmer errors visible as soon as possible in order to correct them.

But yes, it is indeed a philosophy question. I'm fine with this.
