### ISSUE TITLE
Close should be executed on nextTick?

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#33]
Right now if there is a pending flush, commands sent in the same tick as ´close` might fail? Optionally maybe flush before close? I'm not quite sure what would be the proper behaviour.

**Comment by ronag** [comment]
i.e. right now this will not work:

```
nats.flush();
nats.close();
```

**Comment by derekcollison** [comment]
Correct, its Node.js which is an asynchronous language by default, so anything that has io you need to provide a callback to know it was processed.
