### ISSUE TITLE
Share Subscriptions

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#35]
Especially subscriptions that do not have any options could be interesting to use a reference counted sharing for. Would be a nice performance optimisation.

On the other side of the coin. Does the nats server internally share subscriptions to the same client, i.e. if the same client subscribes to the same subject twice I would assume the server will only send matching messages once?

**Comment by derekcollison** [comment]
To keep the protocol simple, no. All of the client architecture is driven by it, so you subscribe and provide a unique client scoped closure that needs to be unique for the client context.

**Comment by derekcollison** [comment]
The interest graph is optimized between servers, but not for clients. You would need a full on subject distributor in each client, it's not straightforward like one might think due to wildcard subscriptions.
