### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#39]
```
node_modules/nats/lib/nats.js:447
        if (psize >= client.inbound.length) {
                                   ^
TypeError: Cannot read property 'length' of null
    at Socket.<anonymous> (/node_modules/nats/lib/nats.js:447:36)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

Possibly user error? Needs some more error checking though as this doesn't give much to go on.

**Comment by derekcollison** [comment]
Any information you can share on what the program was doing when this occurred?

**Comment by ronag** [comment]
Unfortunately no. It only happens sometimes and I haven't been able to consistently reproduce it since.

**Comment by ronag** [comment]
Ok, here is a guess:

When `client.emit('error', m[1]);` the callback could actually decide to close the bus which would set `inbound == null` thus in at line 447 we can get a null reference.

**Comment by derekcollison** [comment]
Thanks, that is helpful.
