### ISSUE TITLE
TypeError: Cannot read property '3' of null

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#40]
```
TypeError: Cannot read property '3' of null
    at Client.unsubscribe (/node_modules/nats/lib/nats.js:740:22)
    at [object Object].action (/src/lib/bus.js:53:24)
```

Probably user error but would be nice with better error messages.

**Comment by ronag** [comment]
Happens when trying to unsubscribe a closed instance. Should probably swallow error and warn.

**Comment by derekcollison** [comment]
Agree this should be cleaner, will get it into next release.
