### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#41]
We are seeing some significant performance issues with this library when processing a lot of mesages arriving in bulk.

I'm seeing our event loop being blocked for 200-1200ms. Which is not quite acceptable.

The first thing we kind of need is to make sure that the nats parser yields back to the event loop so that it doesn't block other things from making progress, i.e. use `setImmediate`, `setTimeout` or `process.nextTick` after every nth message or some other time based heuristic.

Next thing is that the parser seems to be a bit slow, in relative terms.

I don't have time to give better metrics right now. I will come back to this issue later. Our current solution is to run node-nats in a web-worker.

**Comment by derekcollison** [comment]
Which version of Node?

What is your callback doing in terms of processing the message?

When the initial client was written, regex was the fastest way to parse, if you look at the Go client you can see we use a hand written zero allocation parser to process the inbound stream. It may be time for us to revisit this with the node client.

**Comment by ronag** [comment]
It was running in Chrome. Not sure what V8 version is the one used currently.

**Comment by ronag** [comment]
We've run into this one the server as well.

We've done the following change, https://github.com/BoffinsDev/node-nats/commit/57d08ec0a59628e34800ebedec7411de8b42c68b, not pretty but it does the job.

**Comment by derekcollison** [comment]
I looked into how we might be able to balance the response latency when receiving a large number of requests. Calling flushPending() at the tail end of publish() kills throughput by an order of magnitude. But, I can put flushPending() into the flush() call itself. You could either call flush(), or tack on a callback to the publish().

**Comment by ronag** [comment]
@derekcollison: Also there is the latency consideration on the consumer as well. The `flushPending` solves the issue for the producer but not on the consumer side.

**Comment by derekcollison** [comment]
Help me understand. What latency on consumer side? Node.js is single threaded, and we react immediately to 'data' events and delivery messages appropriately. If you spend alot of time in those callbacks you will delay the messages behind them.

**Comment by ronag** [comment]
```
// Producer

for (let n = 0; n < 512; ++n) {
  nats.publish(`foo`, n)
}

// Consumer

const start = Date.now()

setInterval(() => console.log("TICK", Date.now() - start, 40)
subscribe('foo', (msg) => console.log("TOCK", Date.now() - start, 40)
```
Let's say that due to a slow machine each message takes 1ms to parse and execute a very simple callback and 512 messages fit in one 'data' callback from the socket.

```
TOCK 1
TOCK 2
TOCK 3
...
TOCK 512
TICK 513
```

So even though I want "TICK" to print roughly every 40ms it could be delayed for a long time since the nats parsing does not yield.

**Comment by derekcollison** [comment]
So even if it was only one callback for the first message that takes a long time, you think we should yield after a set timeout and setup a processNextTick() for the remaining messages we have received?

**Comment by ronag** [comment]
@derekcollison: I'm not sure I would go that far. If you want a low latency system sending big messages is a design fault.

There are several ways to go about it I would guess.

- Let the user decide, i.e. if the callback returns a thruthy value yield with process.nextTick
- Yield with process.nextTick after a certain timeout on message boundaries.
- Yield with process.nextTick after every message.

**Comment by derekcollison** [comment]
I think the second option makes the most sense when controlled by the user as an option to the system.

**Comment by ronag** [comment]
:+1:

**Comment by derekcollison** [comment]
I am almost completed with the TLS. Once done and working I will get this in. Agree could be a good feature for latency sensitive cases.
