### ISSUE TITLE
There is a missing unsubscribe after a request is finished

### ISSUE THREAD

**Issue by asafyish** [nats-io/node-nats#43]
I see that after using nats.request, the inbox subscription still exists, both on the server, and the client (nats.subs), probably a missing call to unsubscribe after processing the received message.

**Comment by ronag** [comment]
See, https://github.com/nats-io/node-nats/issues/29

**Comment by asafyish** [comment]
Hmm, I mean, the subscription still exists, even after I successfully received and processed a response. No errors involved.

**Comment by ronag** [comment]
That's by design.

**Comment by asafyish** [comment]
Yeah that can work.
Thanks !
