### ISSUE TITLE
Use of `stream.isPaused()` extraneous and breaks Node 0.10.x compatibility

### ISSUE THREAD

**Issue by Ulexus** [nats-io/node-nats#49]
The execution of `resume()` [implies](https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L700) the check to see if the stream is paused.  Thus, wrapping the `resume()` [here](https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L598) is unnecessary.

Moreover, using `isPaused()` breaks compatibility with Node v0.10.x which, while unarguably old, is required for my use case, presently.

**Comment by derekcollison** [comment]
Does 0.10.x understand resume?

**Comment by Ulexus** [comment]
It does.

**Comment by Ulexus** [comment]
TLS is broken in v0.10.x Node, as well.  Not worth adapting, I believe.

**Comment by derekcollison** [comment]
Fair enough.
