### ISSUE TITLE
Oddly affiliated callbacks for publish

### ISSUE THREAD

**Issue by Ulexus** [nats-io/node-nats#51]
The present scheme of processing callbacks for the publish function is a bit strange.  It is roughly akin to:  "I have tried to send your message.  I don't know whether it was sent or not, but after I threw it away, I was able to ping the server and get a pong back."

I feel that a more appropriate use of the callback is:  "I have tried to send your message to the server.  The send [failed|succeeded]."  

This says nothing about the operation of the server... but then, previous message was only a surrogate indicator, anyway.  If the server was unavailable for your message but came up in time to respond to the subsequent 'ping', your app is blithely unaware.  It could indirectly be listening for errors or connection losses, but even then, you won't know if that affected the message you sent or not.

Instead, I think the `publish` method's callback should be very specific in meaning, scoped to only the things it can do something about:  decide whether to try again.

This is strictly my opinion, and I'm very interested in hearing alternative views, particularly since I am rather new to NATS.

**Comment by derekcollison** [comment]
When the PONG is received back from the server, the message has been processed by the server.
So a callback associated with the publish will indicate that the message has been received by the server.

**Comment by Ulexus** [comment]
Perhaps I am missing something, then.... it appears to me that, as a part of the flush function, you are sending a ping and waiting for _that_ pong.

**Comment by Ulexus** [comment]
Here is where I'm talking about:
https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L829

The callback is simply added to the list of pong callbacks and a ping is immediately generated (via a call to flush().

**Comment by derekcollison** [comment]
That is correct, but anything that has been buffered will be sent before the PING, and the server, after processing the messages and the PING will send a PONG.

**Comment by Ulexus** [comment]
Correct; it proves that the queue has been cleared, but it does not say _anything_ about whether the message made it _to_ the queue.

Ref:  https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L542  (if the connection is closed, silently fail)

Ref:  https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L527 (no callback supplied for any sending errors)

Now, it is true that the _latter_ of those failures will probably trigger an 'error' event.  However, that event is dereferenced from the request to send the messsage and thus, relatively useless, from the routine calling `publish()`'s perspective.

**Comment by derekcollison** [comment]
I agree there is an issue with sending/publishing to a closed connection with a callback.

**Comment by Ulexus** [comment]
Personally, I would prefer to buffer outbound messages if reconnect is enabled (up to a reasonable limit), but this is (in my opinion) a reasonable accommodation.  The sender gets an immediate failure notice.

**Comment by derekcollison** [comment]
That is the current behavior, we buffer during a reconnect phase.

**Comment by Ulexus** [comment]
Ah, I had somehow missed that.  I see that, now.... `client.pending`; thanks.

In that case, we just need to capture write errors and disconnected (without reconnect) states, and pass them back.

**Comment by derekcollison** [comment]
Working on that now on the plane ride to the east coast. Should we do boolean for publish or error? Also, publish now throws some errors, if there is a callback provided should we not throw the error but provide it to the callback?

**Comment by Ulexus** [comment]
The argument to the callback should be undefined if no error (as it is now) and an Error (or at least a string) on failure.

Well, we shouldn't _throw_ an error in any case, since you've got the EventEmitter with the 'error' target  (NodeJS will automatically convert it to an exception if it isn't handled).

I don't know that I have a strong opinion about whether to _also_ emit an error if a callback is supplied.
