### ISSUE TITLE
Support binary buffers

### ISSUE THREAD

**Issue by derekcollison** [nats-io/node-nats#60]
Per PR #57 suggestion.

**Comment by jjp91** [comment]
Hello,

I tested the buffer, it goes well and fast.

But the subscriber receive a string.

Could it be possible to get a Buffer type variable?

Thanks by advance.

**Comment by derekcollison** [comment]
In general you will receive a buffer in the subscriber. Although Node could hand you a string as well from the underlying socket.

If you post some code and let me know what you are specifically looking for we can try to help.

**Comment by tutman96** [comment]
I can attest to this as well. The subscription returns a string always. I just pass it through a 
`new Buffer(str, 'binary')` to get it to a binary, but this is definitely less efficient.

**Comment by jjp91** [comment]
Thanks to answer so quickly.

A simple 
nats.publish ( sub , new Buffer(30) ) 

receive
nats.subscribe(sub, function(msg) {
  if ( typeof msg == 'string' )
    console.log( 'It is a string')
}

@tutman96, thk you for the trick.

**Comment by derekcollison** [comment]
Can you send some code snippets that demonstrates that it is always a string? Again, Node.js generally is allowed to select the most performant method of delivering data from a socket. Under load however I generally see it delivering Buffers, not strings. If you only send one small message it may deliver that as a string. You can use 'encoding' option to possibly effect this as needed.

**Comment by jjp91** [comment]
Ok, let's do it like that.

I am not sure to understand what you mean by "use 'encoding' option". Do you mean, as @tutman96 said?

**Comment by tutman96** [comment]
There is an "encoding" option in the creation of the connection. If you set it to "binary", the results from the nats subscription won't be parsed as "utf8" by default. The data is still returned as a string. Essentially the nats library does a 
```javascript
socket.on("data", (buf) => {
    handler(buf.toString(encoding)) //encoding is a Node.js standard encoding (utf8, base64, binary, etc.)
})
```
You can see this at: https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L792
I changing this line to return the buffer raw if the encoding was "binary", however it broke a lot of things and didn't have time to investigate it further.

**Comment by jjp91** [comment]
@tutman96 
Thank you very much for the detailled answer.

With all the respect to the author, this makes me think of a suggestion, if one can forgive me.

I think we can let this line like this but add another one, just after, which would be 
`client.payload.mbuf = mbuf ;`

And at line 873 ( Client.prototype.processMsg) , the original line 
`sub.callback(msg, this.payload.reply, this.payload.subj, this.payload.sid);`

would become
`sub.callback( **this.payload.mbuf ||** msg, this.payload.reply, this.payload.subj, this.payload.sid);`

This would not modify the spirit of the code and let the opportunity to get buffer back.

Thank you again.

**Comment by derekcollison** [comment]
Would you be willing to submit a PR and make sure tests all pass?

**Comment by jjp91** [comment]
Sorry, but i don't know how to do that, even submitting a PR ( what is it? Some kind of change request?).

And about tests, i can test it, if you need, but don't know how to run all of them.

**Comment by AnnapoorniS** [comment]
Is the change available for receiving the binary data at the subscriber end? I could see only string at nats sub. Is there a way to configure in latest code available?

**Comment by StarpTech** [comment]
@AnnapoorniS I think you are looking for 
```js
// PreserveBuffers

// To prevent payload conversion from a Buffer to a string, set the 
// preserveBuffers option to true. Message payload return will be a Buffer.

nc = nats.connect({'preserveBuffers': true});
```

**Comment by AnnapoorniS** [comment]
Thanks! @StarpTech
