### ISSUE TITLE
Lack of visibility into connection handling and status

### ISSUE THREAD

**Issue by jmealo** [nats-io/node-nats#64]
After upgrading to Node 5.x (nats 0.5.4) from 4.x (nats 0.4.4) I'm no longer able to connect (I get a connection timed out). While troubleshooting that, I decided to add event listeners for all connection related events that I saw being emitted from the library. I noticed that only the error events seem to be emitted in a connection timed out scenario. This creates a blind spot when it comes to connection handling.

I noticed the following:
1) There is no ``connecting`` event (or ``retrying``) to monitor connection status/progress
2) Since ``connect`` calls a constructor under the hood and returns a client synchronously; the included examples lack robust error and connection handling.
3) There is no example of how to configure the timeout, it seems to be ``connection attempts * connection delays`` (both look like they're constants).

Here is an example of the code:

```javascript
nc.on('error', function(error) {
   if (process.env.NODE_ENV !== 'production')  {
       throw error;
   } else {
       console.error('NATS: Error ', error);
   }
});

nc.on('reconnecting', function() {
   console.log('NATS: reconnecting...');
});

nc.on('disconnect', function() {
   console.log('NATS: disconnected');
});

nc.on('connect', function() {
   console.log('NATS: connected');
});

nc.on('reconnect', function() {
   console.log('NATS: Reconnected');
});
```

**Comment by derekcollison** [comment]
What was the underlying issue as to why you could not connect?

I will take a look.

**Comment by jmealo** [comment]
@derekcollison It ended up being a connectivity issue (VPN problem). Once that was resolve I was able to connect with the latest version of Node and NATS.

**Comment by derekcollison** [comment]
Does this address your concerns?

https://github.com/nats-io/node-nats/blob/waitOnConnect/test/connect.js#L62

**Comment by jmealo** [comment]
@derekcollison that works for me, some people might find a 'connecting' event helpful, but I'm more interested in detecting failures/retries.

Thanks!

**Comment by derekcollison** [comment]
Would that only be for the first connection for any server listed? Then other subsequent events would be reconnecting?

**Comment by jmealo** [comment]
@derekcollison I would assume that in order to be "reconnecting" it implies that you've "connected" to the service. That being said, if you try server 1, then server 2, then you connect to server 3, server 1 and server 2 did not have "reconnecting" events.

It may be better to pass an object that contains something roughly equivilant to this:
```javascript
{ attempt: n, maxAttempts: n, server: serverCount: n }
```

**Comment by derekcollison** [comment]
That might be a good idea. Let me think on it a bit. The timeout one could be tricky.

**Comment by derekcollison** [comment]
@jmealo Would this object only be on reconnecting, or on connecting as well?

**Comment by derekcollison** [comment]
@jmealo FYI, you have all of this information already if you look at the connection.

Here is a util.inspect of the connection (abbreviated) from a test I ran..

```js
nats_connection is  {
  options: 
   { verbose: false,
     pedantic: false,
     reconnect: true,
     maxReconnectAttempts: -1,
     reconnectTimeWait: 20,
     encoding: 'utf8',
     tls: false,
     waitOnFirstConnect: false,
     url: 'nats://localhost:1426' },
  user: undefined,
  pass: undefined,
  encoding: 'utf8',
  servers: [ Server { url: [Object], didConnect: true, reconnects: 0 } ],
  ssid: 1,
  subs: {},
  reconnects: 39,
  connected: false,
  wasConnected: true,
  reconnecting: true,
  server: null,
  pending: [],
  pongs: [],
  pSize: 0,
  pstate: 0,
  info: null,
  infoReceived: false,
  currentServer: 
   Server {
     url: 
      Url {
        protocol: 'nats:',
        slashes: true,
        auth: null,
        host: 'localhost:1426',
        port: '1426',
        hostname: 'localhost',
        hash: null,
        search: null,
        query: null,
        pathname: null,
        path: null,
        href: 'nats://localhost:1426' },
     didConnect: true,
     reconnects: 0 },
  url: 
   Url {
     protocol: 'nats:',
     slashes: true,
     auth: null,
     host: 'localhost:1426',
     port: '1426',
     hostname: 'localhost',
     hash: null,
     search: null,
     query: null,
     pathname: null,
     path: null,
     href: 'nats://localhost:1426' },
  inbound: null }
```

**Comment by derekcollison** [comment]
So we can open it back up, but I think you have the information that you need already in the callback.
