### ISSUE TITLE
Won't reconnect unless first connected

### ISSUE THREAD

**Issue by ronag** [nats-io/node-nats#65]
This is an issue for us. We usually start up all our systems and then have to wait 5-10 minutes for the switches to startup. But when they start up our nats application won't reconnect, it has already failed.

This behaviour should probably be configurable...

**Comment by derekcollison** [comment]
So you would want the application to continue to continue for some specified interval even if the first connection?

Would it not be better to just keep relaunching the application? Meaning fail fast, etc?

**Comment by ronag** [comment]
> Would it not be better to just keep relaunching the application? Meaning fail fast, etc?

Yes, in most cases. However, if the application is badly designed and has other services that would function even if the nats connection is failing it would be good...

In our specific case we have a quick fix application that provides 2 different services against 2 different nats servers...

**Comment by ronag** [comment]
Another example would be an application that provides both a REST API and a NATS API. If the NATS connection fails the REST API should still work...

**Comment by derekcollison** [comment]
Isn't it fairly straight forward application logic to setInterval() in trying to connect for the first time?

**Comment by ronag** [comment]
You mean we should add the same logic that already exists in node-nats again?

**Comment by derekcollison** [comment]
For the first connect, I don't believe that code exists in node-nats, but let me take a closer look.

**Comment by derekcollison** [comment]
This work for you?

https://github.com/nats-io/node-nats/blob/waitOnConnect/test/connect.js#L62

**Comment by derekcollison** [comment]
You ok with 'reconnecting' for the event or do you think we put the effort and make it 'connecting'? Would that be only for the first one or for ever first connect per server?

**Comment by ronag** [comment]
`reconnection` is good.
