### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by xogeny** [nats-io/node-nats#68]
The latest versions of TypeScript can pull typescript definitions from an NPM repository.  This helps
ensure that the TypeScript definitions are always in sync with what is published in node.  Furthermore,
it makes it much easier for TypeScript users to use the node module because all the have to do is
'npm install nats' and they automatically get TypeScript definitions.  With Angular2's adoption of TypeScript (and TypeScript's rising popularity, in general), this level of support for TypeScript will make life easier for a lot of developers.

All this means, for the `nats` developers, is including **one file** in their package.  It doesn't force any of you users to know or use TypeScript.  It just provides a definition file that can be found automatically by the TypeScript compiler.

Would you accept a pull request for such a definition file to be redistributed with the `nats` package in `npm`?

**Comment by derekcollison** [comment]
Feel free to send a PR, happy to take a look.

**Comment by tutman96** [comment]
I have created pull request #77 to address this issue. Please let me know if I did this process correctly.

**Comment by tutman96** [comment]
Pull request #77 fixes this issue. It is available in v0.6.4. This can be closed now.

**Comment by derekcollison** [comment]
Thanks.
