### ISSUE TITLE
Golang based server that acts as a nats client

### ISSUE THREAD

**Issue by joeblew99** [nats-io/node-nats#70]
I need various browser clients to participate in a pub / sub style topology.
I am a golang programmer and so was wondering if there is a project to expose nats pub / sub to browser clients over any of the usual suspects such as websickets, long poll, SSE ?

The reason I prefer not to go with a nodejs approach is many, but mostly because I need to run on arm v6, v7 and v8 on Linux and windows. 

It's of course perfectly possible that the js code in this repo can be used by  browsers. I would then just need to write a golang server to expose the nats events over websickets. The js code would then be a proxy client to the golang server. 
This is exactly how I would like to architect this, and so I am wondering if anyone could give me some opinions on this before I start coding it.

**Comment by mcqueary** [comment]
@joeblew99 So, bottom line, you're looking for websocket support out to the browser?

**Comment by mcqueary** [comment]
Closing this in favor of nats-io/roadmap#4.
