### ISSUE TITLE
Wildcard subscription does not capture reply messages

### ISSUE THREAD

**Issue by jfathman** [nats-io/node-nats#74]
This wildcard subcription code:
```
nats.subscribe('*', function (msg, reply, subject) {
    console.log(Date(), '[' + subject + ']:', msg);
});
```
displays the 'request' message from a nats.request(), but not the 'reply' message.

Is that expected?  Is there a way to see both legs of a NATS Request/Reply message transaction from a wildcard subscribe?  I hoped to use this as a simple message debug monitor, but need to also see the reply leg to observe all the message traffic.

Thanks for NATS.  It's great.

**Comment by kozlovic** [comment]
Try subscribing to `>` instead. Replies, unless you create your own, is an inbox, which has more than one token. The wildcard `*` is for a single token.

**Comment by jfathman** [comment]
Thanks @kozlovic, I will try that tonight.  Appreciate your quick response.

**Comment by jfathman** [comment]
Confirming for future readers that `>` works great, can trivially monitor request and reply messages.
