### ISSUE TITLE
subscribe handler exception lead nats client work strange

### ISSUE THREAD

**Issue by roytan883** [nats-io/node-nats#75]
nats.subscribe('foo.bar.*', function(msg, reply, subject) {
  console.log('Msg received on [' + subject + '] : ' + msg);
  fnABC()
//if exception happened in fnABC() , the nats client will behave strange
//the msg will be random string 
//or the subscribe can't receive any furture incoming msg
});

**Comment by derekcollison** [comment]
Agree, but for the callbacks that work fine, wrapping with a try/catch is expensive and hurts performance. If its important to you, simply curry a function with try/catch or place them in the handler callback directly.
