### ISSUE TITLE
Not an issue, just thumbs up!

### ISSUE THREAD

**Issue by 1N50MN14** [nats-io/node-nats#76]
@derekcollison Thanks for making nats available, absolutely love how you kept it simple! I put together a fully functioning pubsub into my containers, set up a survey for health checks, a simple Dockerfile for dynamic configuration of new cluster nodes - nats.io > docs > implementation in under 90 minutes this bad boy just just *works*!

**Comment by 1N50MN14** [comment]
closing

**Comment by derekcollison** [comment]
Thanks..
