### ISSUE TITLE
Adding of new server to client

### ISSUE THREAD

**Issue by 1N50MN14** [nats-io/node-nats#78]
I understand that automatic syncing of clients with servers is planned, in the meantime, is there anything that prevents me from "manually" adding new servers myself once a client have been constructed? I see `servers` is an exposed property, the client constructor loops through `servers` opts and pushes them to servers here https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L231

`Server` on the other hand is a private API https://github.com/nats-io/node-nats/blob/master/lib/nats.js#L252 but it's a simple object which I can either override or expose outside the client.

Alternatively if you expose `Server` then I can do something like `nc.servers.push(new nats.Server(uri))`.

**Comment by derekcollison** [comment]
Feel free to submit a PR to expose Server such that you can do this. I would also add an entry point to add a new Server instead of pushing directly. This could just take a URI so then you would not have to expose Server.

**Comment by 1N50MN14** [comment]
Yup makes sense, àddServer(uri)` sounds good?

**Comment by derekcollison** [comment]
I think so.

**Comment by 1N50MN14** [comment]
Ok, then submitting a PR any point in adding a test for that?

**Comment by 1N50MN14** [comment]
n"m I can use nc.close() to test

**Comment by derekcollison** [comment]
Yes please always submit tests for any new functionality or bug fix, just good hygiene.

**Comment by 1N50MN14** [comment]
PR submitted

**Comment by derekcollison** [comment]
We need to add some more logic since we normally randomize the array. So we should test that is the case when you add, so we can push but then need to randomize unless there is a flag to suppress.

**Comment by 1N50MN14** [comment]
Closed in #79

**Comment by 1N50MN14** [comment]
Would it be possible for you to bump version and publish to npm when you got some spare time?

**Comment by derekcollison** [comment]
Yes, I may have a few more things to land first, that ok timing wise or would you prefer earlier?

**Comment by 1N50MN14** [comment]
No worries for my part it can wait 1 - 1.5 weeks
