### ISSUE TITLE
Option to discard real-time data message if not currently connected to gnatsd

### ISSUE THREAD

**Issue by jfathman** [nats-io/node-nats#80]
I am running gnatsd 0.8.0 (ARM version) and the nats 0.6.2 client for Node.js on Raspberry Pi 3.  It works great.

My application publishes IoT sensor data messages that are only meaningful in real time.  But if gnatsd is not running for an interval, the client queues published messages and then delivers them in a burst when it is next able to connect to gnatsd.  I need to prevent that burst delivery of accumulated stale sensor data.

As an application level workaround, I can track connected true/false state based on the connected, reconnected, disconnected, and closed events and only publish if connected is true.  But that requires wrapper logic for every call to publish and a global state variable.  It gets a bit messy.

Or I can reach into the nats object and only publish if nats.connected is true.  That eliminates the global state variable, but assumes a nats internal state variable that is not exported in the official API.

It might be useful if there were a new global option for nats.connect() and/or a per invocation option for nats.publish() where the application could specify the message should be discarded if gnatsd is not currently connected.

Have I missed something?  Is there already a way to do this?

Thanks for the excellent open source NATS software.

**Comment by derekcollison** [comment]
Thanks for your note. I would suggest suppressing reconnect, and then placing a disconnected handler on the connection and re-establishing the connection yourself. This would prevent messages from being buffered while disconnected I believe.

```
    var nc = NATS.connect({'port':PORT, 'reconnect':false});
    nc.on('close', function() {
      nc = NATS.connect({'port':PORT, 'reconnect':false});
    });

```

**Comment by jfathman** [comment]
Thanks @derekcollison, I hope to try that soon.  May be after the holiday weekend.

**Comment by derekcollison** [comment]
Sounds good. Keep us posted.

**Comment by jfathman** [comment]
I tried suppressing reconnect, @derekcollison, and it works, but I lose the useful built-in NATS reconnect logic.  I could reimplement reconnect at the application level, but took a different approach.

This code creates a wrapper function that only publishes the message if the NATS connection is currently open.  NATS events are used to update connection state without resorting to a global variable so everything is self-contained.  The wrapper function returns true or false to indicate whether the message was sent or not, in case the application cares about that.

This approach does require calling nc.publishRealtime() instead of nc.publish(), but that is self-documenting and easy to refactor if official NATS someday adds an equivalent option to publish(), and perhaps a true/false return.

This is only lightly tested so far, but appears to work well, discarding messages when the connection is down, and preserving the useful NATS reconnect logic.

```javascript
nc = nats.connect({ 'servers': config.natsServers, waitOnFirstConnect: true });

(function makePublishRealtimeWrapper(nc) {
    if (nc.publishRealtime === undefined) {
        var connected = false;

        nc.on('connect',    function () { connected = true; });
        nc.on('reconnect',  function () { connected = true; });
        nc.on('disconnect', function () { connected = false; });
        nc.on('close',      function () { connected = false; });

        nc.publishRealtime = function(subject, msg, opt_reply, opt_callback) {
            if (connected) {
                nc.publish(subject, msg, opt_reply, opt_callback);
                return true;
            } else {
                return false;
            }
        }
    }
})(nc);
```

```javascript
if (!nc.publishRealtime('sensorData', JSON.stringify(msg))) {
    console.log(timestamp(), 'sensor data discarded');
}
```

**Comment by derekcollison** [comment]
Do you want the publish to fail or would you prefer to be able to configure how long nats should hold onto queued messages?

**Comment by jfathman** [comment]
Specifying retention aging could be very useful.  The last (few) sensor readings still have value, and as you intimate, the value is more about time (age) than count (depth).  One second resolution or less would be ideal (depends on the application and sensor publishing rate), and retention age zero could indicate retain none.  Some way to know if and how many messages were discarded could be useful.

**Comment by aricart** [comment]
Closing this issue, currently, this doesn't line up with any of the existing clients, and while cumbersome handling the connect/disconnect/reconnect handlers should provide enough state to the client to disable publishing of messages while the nats client is disconnected.
