### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by 1N50MN14** [nats-io/node-nats#81]
It would be great if we could get nats to work over websockets (imho), in theory we just need to shim `net`, is it ok if I give it a go and send a PR?

**Comment by 1N50MN14** [comment]
will also need a websocket <> tcp proxy, I can write that as a separate module

**Comment by ronag** [comment]
https://github.com/nats-io/node-nats/pull/21/files

**Comment by 1N50MN14** [comment]
oh interesting your PR looks spot on @ronag you even added the `browser` tag in `package.json` shame it didn't make it into the repo. Are you using that in production and if so any unexpected behaviours you noticed? tack ;)

**Comment by ronag** [comment]
Det funkar fint. Vi använder det i produktion.

**Comment by 1N50MN14** [comment]
supert, tack for det. Closing issue for now.

**Comment by 1N50MN14** [comment]
closing
