### ISSUE TITLE
Stream buffer left dirty when stream is closed

### ISSUE THREAD

**Issue by abstractvector** [nats-io/node-nats#9]
When the stream is closed, the `client.inbound` is not cleared. This means that when the client reconnects, it starts with a dirty buffer onto which new stream data chunks are appended. Consequently, if the stream is closed in the middle of receiving a message, parsing will fail when the stream reconnects. See here: https://github.com/abstractvector/node_nats/commit/3c274d0cceee8808a26d958a2b714ba06ee30dbf

**Comment by derekcollison** [comment]
Working on this now.. Had some bad processing in error handling too, but have a test case to reproduce, fixed error handling, and clearing inbound works on reconnect now.
