### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by mkozjak** [nats-io/node-nats#92]
We should have proper library API documentation showing in detail how we can use all the provided methods.

Currently all we can do is look into the source code. I haven't found anything on the official NATS website indicating all the clients should have similar API or something, so I cannot assume anything.

In example: I just realized there's a 'json' field that can be passed to 'connect' via source code.

Edit: Seems like the source code does have a documentation but it's only there and nowhere else (compiled). Is that a YUIDoc or something?

**Comment by aricart** [comment]
The documentation in the nats.js library is commented. The index.d.ts (intended for typings but also works great for IDE integration) has clear and concise docs on all the public API methods, options and types. The [README.md](https://github.com/nats-io/node-nats) also shows sample code for all the public API. 

Was there some other API calls that you were missing or wanted more clarity on?
