### ISSUE TITLE
token cannot work

### ISSUE THREAD

**Issue by gaozhidf** [nats-io/node-nats#96]
hi, 

i try to use token auth, but it seems failed
```
var nc = nats.connect({'url':"nats://localhost:4222", 'token': 'mytoken'});
```

and then i try it as url param, but it seems it just set `mytoken` into username 
```
// Connect with token in url
var nc = NATS.connect("nats://mytoken@localhost:4222");
```

**Comment by aricart** [comment]
Found the issue. The version of nats from npm registry doesn't support token authentication. This was added to master on 7/19/16 but was not pushed to npm. Let me try and refresh that.

**Comment by aricart** [comment]
0.6.8 just pushed to npm fixes this issue.

**Comment by gaozhidf** [comment]
thanks a lot

**Comment by gaozhidf** [comment]
thanks a lot

**Comment by gaozhidf** [comment]
thanks a lot

**Comment by aricart** [comment]
👍
