### ISSUE TITLE
request doesn't support rpcTimeOut

### ISSUE THREAD

**Issue by sfrooster** [nats-io/node-nats#97]
Unlike csharp and java, a "request/reply" action doesn't seem to allow for a timeout after which the request is auto-failed.

**Comment by aricart** [comment]
Sure it does! The timeout is not specified with the request. Instead there's a timeout function that you can call and associate with the subscriber id (returned by subscribe and request). Here's an example.

```
#!/usr/bin/env node

'use strict';

var nats = require('nats').connect();

nats.on('error', function(e) {
  console.log('Error [' + nats.options.url + ']: ' + e);
  process.exit();
});

var sid = nats.request("foo", {'max':1}, function(e) {
  console.log('callback called: ' + e);
});

nats.timeout(sid, 1000, 1, function(sid){
  console.log('the subscriber timedout: ' + sid);
});

```
